### ISSUE TITLE
Why using two antennas?

### ISSUE THREAD

**Issue by ystreibel** [azrod/diy-rflink-pcb#1]
Hello,

First, thanks for your really good jobs for this rflink pcb.
I just have question about the fact that you decide to use two antennas for this project.

What is the point that I probably missed to not use the same antenna between the STX882 and the RXB6 ?

**Comment by azrod** [comment]
Hello,

Thank you for your message.

I used two antennas because on the RFLINK documentation (http://www.rflink.nl/blog2/wiring) each component uses its own antenna. One who transmits and one who receives

Hoping to have answered your question
