### ISSUE TITLE
Gnd 



### ISSUE THREAD

**Issue by psy501** [azrod/diy-rflink-pcb#2]
Thanks again for this superb card, I am soldering the components but there is a question that I ask myself, where and how is the ground connected?

![Screenshot_20241210-161805.png](https://github.com/user-attachments/assets/dc6241f2-1f92-43a2-bfb5-770ce5e355dc)

**Comment by azrod** [comment]
Hi @psy501, 

Sorry for the delay. 

The GND is present throughout the board (lower layer)
These 4 GNDs are there to be able to reuse them for other components connected to the arduino.

> Thanks again for this superb card

Many thanks :heart:

**Comment by psy501** [comment]
Ok thanks 😙
